apiVersion: v1
kind: Pod
# kind: Service
# kind: ReplicaSet
# kind: Deployment
metadata: 
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: busybox